### ISSUE TITLE
PR to seaborn?

### ISSUE THREAD

**Issue by josesho** [mparker2/seaborn_sinaplot#1]
This is fantastic work! Have you considered making a PR to seaborn? Be happy to assist. Again, super happy this has been implemented for Python/seaborn.

**Comment by mparker2** [comment]
thanks :) not sure if this is a popular/mainstream enough vis method for seaborn to want it, I suppose it would be worth asking though! The code would probably need an overhaul, at the moment its a bit of a hacking together of `sns.ViolinPlotter` and `sns.StripPlotter`.

**Comment by josesho** [comment]
I think having both the swarmplot AND the sinaplot would give users more choice in showing their data; quick experiments with your package indicate swarmplots work up to Ns of ~100, sinaplots are much better at handling Ns of > 500, showing both all data and the underlying distribution.

I'm not familiar with the underlying seaborn codebase (it looks dauntingly complex); your package might be the entry point I need. I can help with some documentation to start with.

**Comment by mparker2** [comment]
yeah thats true although once you get up to >500 points it'd probably hard to see & count the individual points in the sinaplot anyway so I'd probably revert back to a violin or boxplot. swarmplots are definitely too slow!

sounds good!

**Comment by terrycojones** [comment]
Hey @mparker2 - thanks for writing this code & sticking it on GitHub! Results look really good. I'll probably use the plots in a paper I'm working on & will cite you.  Thanks again, Terry.
