### ISSUE TITLE
For your interest...

### ISSUE THREAD

**Issue by davidbestue** [mparker2/seaborn_sinaplot#2]
HI! This is a super nice work!! :D 
I though you would like to know I have used your function to implement a versatile type of plot that, in my opinion, gives the right amount of information (distribution, CIs by bootstrap (with all data and in a subject base), with diferent aesthetic options to plot the means, legend... all on top of your sinaplot and keeping a "seaborn language" 💃 

If you are intereseted, check it on my github. It is in the repositore called: "funciones" under the name "linares_plot.py". In the README you will find some examples.

All the best and thank you :D

**Comment by terrycojones** [comment]
Hi from me too. I've been using your code for the last 5 months and it's great. I just cited you in a paper to be submitted. Thanks!!

**Comment by davidbestue** [comment]
Great!!! I would love to see them whenever is out! Congrats for the paper :)
